### ISSUE TITLE
KDE Commit > 3.5.2

### ISSUE THREAD

**Issue by Andre87osx** [Andre87osx/AstroPi-system#14]
- [ ] 4194cd472168e4d9cc3086618a511b7a8a448cdb - Start KStars v3.5.3 development cycle
- [x] 171afe98f35b63f50328a31c565c1f830d4bf296 - Add hour angle and Zenith angle to info focus label. Should fix #52
- [ ] 2a36bd783973120d071e2814b8c3538db29152aa - Robust star correspondence.
- [x] 0cfba9f39c0dd359d3b13b3f1894e4b860260e15 -  adds manual slew complete command
- [ ] e15235060d77df3c0959fd0a6935659f9ad12f5e - Updating CMakeLists to copy Data directory into the app bundle on Mac
- [x] b5139b2f1f2e20f4dcdb7931bbf4d477534c8f89 - Test for invalid declination after jnow conversion
- [x] 5e41fdd3d82b6d4ff9136570fc24d14f06a3674e - Make sure to remove trailing slash to avoid potential issues when creating the path
- [x] cf3d3b2f9e0559f27677e28642ab642ac2a2933d - Fix error reporting when saving a FITS image. Save bayer data to disk in case...
- [x]  197893089069c9668d16108b0290dda5658bd2bf - Make multi-star sep default algorithm
- [x]  26c401b377a429c6303cbf2ba899eae1c9754a50 - Rename gpg to gpg_enabled
- [x]  24654a4000f37155478b38043f202351d2ce0465 - Reset mount park state after an error
- [x] 6a45cb448927a66b4d7e40b737306c8d25c28f58 -  Check if file is temporary
- [ ]  b364af8b564fcdd76144b828d3f3bbedb39a7fe2 - Added myself to contributers list and updated Bahtinov focus documentation
- [ ]  5a8b3db5159611948417a67ed5c876d62a41ea9a - No need to set general settings for PAH
- [ ]  c8501203153c847f21b8876da068e56a13a85c9d - Temprary files were used in FITSData before when we used to save files...
- [ ]  581c7ab7729be674eff87772e3c52f85f0317eea - Meridian flip test case simulating current behavior
- [ ]  96262250a73544ccbb312635a2c625599fbcd800 - Fixed terrain icon. Add pixel interpolation to improved render quality....
- [ ]  cc72a39afb3044c65f571a36feff44ff13d92e6c - Accept target position when it is at minimum HFR value
- [x]  8ae0d8e106970e51e2725c11a73021f591cdf2fd - Reset inSequenceFocusCounter after meridian flip otherwise autofocus will never run post-meridian
- [ ] 66d10a8241b21f35ff5e95b999207835d7dce5a3 - When Adaptive Sampling is on, m_PreviewSampling is changed dynamically...
- [x] 46ba38039e7286f54af60ba026a790d454747a0a - Fix EQ Grid scaling
- [x] c3149b32eac1d3a00ac5e537c134cc127052b24d - Update docs for the new 'Terrain' config page
- [ ] dcf5b19b8f6bcf570ca2761ebb077f456526f02f - Rimuovere suggerimenti di dimensioni aggiuntive che interrompono le traduzioni
- [ ]  4411913c0999f599300d90619c1b121d0affe197 - Add i18n()
- [x] 5235347acc27c2c4e4c6f5f851bb930fe23b9115 - Enable device.group.property type subscriptions
- [x] 68f8af777e35fd41ac2ada3fa8838cb15153a538 - Update opsekos.ui - Fix minor typo in Ekos Scheduler settings.
- [ ]  77a2226ee2c2456a358e31bd0c02c334f05adebc - Improve performance when loading large frames and multiple calls to...
- [x] 7cf7e7595bc94e4bb8e0f205e0aa29d053378c46 - Add one more check for non-guide dither to prevent both options being on at the same time
- [x] a974b20b22d7b7626d3985eb1d0f2f57d4882333 - Add feature to append Scheduler jobs to queue.
- [ ] 4acb61da8324a4ad36084370d103f8737854dd54 - Rework Mosaic Tool.
- [x] 4d7670306ba70c305802aeb87f965f2774aba2b6 -  Using QJsonArray for groups and properties
- [x] f17b4ad191fe46760bf3550fef6750052f316eea -  INDI Driver sync
- [x] 02786347609a292c38ff8f27ff57112488781cb6 -  Add a variable to see if stretching in progress so that we immediately update...
- [x] fed08b51ab0ca9349589630d9804ed175d04909e -  Messages.sh: use python3 directly
- [x] 81deef937b83d9ea2e0d379d773ca82b8fefb490 -  Consenti solo 5 guide perse consecutive.
- [x] 0c42fa8553d99c269bfd80eed933949d2ab8a071 - Add button to purge all KStars configuration
- [x] 00bc2a4dbc5ece0c3a1423dbd20c189b0c162dd9 - Do not keep hash of INDI properties, use them directly from basedevice
- [x] 0344a9b061d9cef635559d46321c6a584aac5e7a - Simplify the polar alignment star selection message during refresh
- [x] 113ec76e608b23e88cc56669fff66763cbaea5b2 -  Turn off show terrain if file fails to load
- [ ] a952152cf689eb38dcf5f34d439817bd0f853383 - Add method to sync options to GUI if changed
- [x] ff36c9bb1decab5a4f435e31bd63534fa0a89854 - Messages.sh: fix warnings, consistently use gawk
- [ ] c14c1d21775023698c3a579ed436ba714b6faca8 - Fix warning
- [ ] 512eb466174cdfcd0fd5d6a19e1bf5188ece85a5 - Fix UI element names to match kcfg_ requirements
- [x] c669f4317c20b2f007dd034448411d09356caf0b - Preemptive shutdown should be on by default in case scheduler decides to sleep...
- [x] 37013d0558223e7d0ea01671c708babfa8d819b7 - Use better description for terrain
- [x] 69f1b7d9a7bbf18bcddc59a169434333e7b93175 - Add generic and proxy devices to the list before cleaning device
- [x] e5a3a24b0faec02a0bd98617bcee1081b900a331 - Fix sexigesimal handling in EkosLive
- [x] f9eb62d96bb30c46f6488099a2d95b590268e38b - Fix issues editing artificial horizon.
- [x] d2bfcf724c2a8a2efe2e7f1b0f81ef360c37d7d4 - Fix calculation of remaining time for job
- [x] b99758764e23fdaa2d247f292a9121b849bf7e19 - Fix dbus properties
- [x] 57ccba3fc3a6c5187256a10e50e2117917ab666f - Test Scheduler::processJobInfo in preparation of issue #54
- [x] ccd592aa2a6f47aad10fac7cbe5e0a1e7e143213 - INDI drivers sync
- [x] 205bb112896a66a7f298509b32ccd7b1e2ed06fa - Add support to Olympus ORF files
- [x] 1c964bf33b51cfe0b5efba3a78d92d4cae8b1293 - Add option to configure INDI server transfer buffer size
- [x] 870c1989ebc520e7e347f9ef355a1bf6e372146b - reset currentPort to start - 1 otherwise it would start on 7625
- [ ] f11e32f8991028f18a9ec02ea642f24ece7f1724 - Make default locations of executable dependencies configurable
- [x] a5e518d9856ce427bb5dbcbda93aebaa5d076e4d - Add channels to metadata
- [x] 2010da2e7867a32d2cf2702b0f4ac710ed7bf0d9 - Redo of artificial horizon.
- [x] 0105b52494d47cbe0c730854ae5a3b78b6cf1a8d - Fix copy coordinates when clicking on an empty coord. After we get the catalog coord J2000, we need to reset the JNow coords to the same object
- [x] ca4ea129749a1d0292058c455474eaabaf2259e4 - No need to add fits keywords just for filter. Let KStars set filter to empty when no active filter is used
- [x] 424cf2d35d9ec2653a961f24c13d7ac93147d470 - Fix align table missing status icon updates at times. Introducing a function that is called everytime we need to update the cell
- [x] b6b20605ce9296f6e66541e68fb46ce4443192ba - Test Scheduler::processJobInfo in preparation of issue #54
- [x] 91971ff3162897c0d7f87e9017faa2862fd48162 - Add more explicit stops for capture timeout
- [ ] 800e7a65e2889e760126d9846f499f5d3dc93e6a - Add PHD2 timeout for reconnecting. Add configurationchange paramter
- [ ] 685d15ccbb0b97bcfad2115fe398c1ee85d0fed9 - errorOccured is available only for 5.15+
- [x] ab94144bca17e00486d8c583d8357ee822bc854b - Check for camera on stopping focus in case it was removed
- [x] 1785e50c5c2301562749ed1545785897b64f7bb1 - A New Dark Frame Library
- [x] ed3ca8341141729ac25e9f38002a3b99bb5fffe3 - Improve loading performance and reduce the timer to 50ms
- [x] ed2f9546f97ee3c8f588632563ae20acfaa3a8fa - Clear device subscrption when required
- [x] e3d41b0fd47bced02557f6922572e3674aaf537d - Fix a few more issues raised in the MR review
